version: '3'

volumes:
  exec_data:

services:
  redis:
    image: redis:6.2.6
    command: --port 5040
    ports:
      - "5040:5040"
    networks:
      - default
  qc-script-splitter:
    image: planqk/qc-script-splitter:latest
    command: sh /startup.sh
    ports:
      - "8889:8889"
    environment:
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    networks:
      - default
  rq-worker:
    image: planqk/qc-script-splitter:latest
    command: rq worker --url redis://redis:5040 qiskit-runtime-handler
    environment:
      - FLASK_RUN_HOST=qiskit-runtime-handler
      - FLASK_RUN_PORT=8889
      - REDIS_URL=redis://redis:5040
      - DATABASE_URL=sqlite:////data/app.db
    volumes:
      - exec_data:/data
    depends_on:
      - redis
    deploy:
      replicas: 1
    networks:
      - default
networks:
  default:
    driver: bridge
