"""empty message

Revision ID: 3bbbe64f902d
Revises: dcc8559ddd89
Create Date: 2022-03-09 16:44:12.183240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bbbe64f902d'
down_revision = 'dcc8559ddd89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('program', sa.LargeBinary(), nullable=True),
    sa.Column('agent', sa.LargeBinary(), nullable=True),
    sa.Column('error', sa.String(length=1200), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    # ### end Alembic commands ###
